"use client"

import "./globals.css";
import NavBar from "./components/NavBar";
import { usePathname } from 'next/navigation'



// export const metadata = {
//   title: "Create Next App",
//   description: "Generated by create next app",
// };


export default function RootLayout({ children }) {
  const pathname = usePathname()

  return (
    <html lang="en">
      <body>
        <div>
        {pathname !== '/' && <NavBar />}
        <main>{children}</main>
        </div>
      </body>
    </html>
  );
}
